### ISSUE TITLE
[Flow] Logs Explorer user flow for 90 day data

### ISSUE THREAD

**Issue by ruflin** [elastic/oblt-playwright#6]
This is an issue to bring up user flows I would like to see tested / automated around Logs Explorer. The numbers are as an example for now. 

* Ingesting 100GB of Logs for the past 90 days 
  * 50GB nginx access logs
  * 50GB system logs
* Opening Logs Explorer, time range is last 15min for now
* Opening Integrations selector, filter down by nginx access logs
* Expand time range to 90 days
* Click on one document to see logs detail view

**Comment by ablnk** [comment]
I suggest we separate user flow automation part from data generation, which I have added as action point to [this meta issue](https://github.com/elastic/oblt-playwright/issues/1).  @adam-stokes FYI
Here is a test script for Logs Explorer https://github.com/elastic/oblt-playwright/commit/a7c5106ea4c8a79554ecc003f2d1f092de4e72c4
You can set any time range you want to test by passing it to [.env file](DATE_PICKER).
